/* unicode.c – Unicode® support routines
 *
 * Sections:
 *   § Core Specification
 *   § Annex #11 – East Asian Width
 *   § Annex #29 – Text Segmentation
 *
 * Data tables are generated by tables/generate_unicode_tables.py
 */

#include "unicode.h"
#include <stddef.h>
#include <stdlib.h>

/*--------------------------------------------------------------------
 * Type definitions for data tables
 *--------------------------------------------------------------------*/


/*--------------------------------------------------------------------
 * Core Specification
 *--------------------------------------------------------------------*/

/* Test for combining character property */
bool
unicode_is_combining(rune_T r)
{
    return false;
}

/*--------------------------------------------------------------------
 * Default Case Algorithms
 *--------------------------------------------------------------------*/


/* Simple uppercase: ASCII fast path + table lookup */
rune_T
unicode_simple_toupper(rune_T r)
{
    return r;
}

/* Simple lowercase: ASCII fast path + table lookup */
rune_T
unicode_simple_tolower(rune_T r)
{
    return r;
}

/* Simple case fold: ASCII fast path + table lookup */
rune_T
unicode_simple_fold(rune_T r)
{
    return r;
}

/*--------------------------------------------------------------------
 * Annex #11 – East Asian Width
 *--------------------------------------------------------------------*/

/* Return East Asian Width property for r */
unicode_east_asian_width_T
unicode_east_asian_width(rune_T r)
{
    return U_EAW_N;
}

/*--------------------------------------------------------------------
 * Annex #29 – Text Segmentation
 *--------------------------------------------------------------------*/

/* Return Word Break property for r */
unicode_word_break_T
unicode_word_break(rune_T r)
{
    return U_WB_Other;
}

/*--------------------------------------------------------------------
 * Identify characters that act as word-segmenting spaces
 *--------------------------------------------------------------------*/

bool
unicode_is_w_seg_space(rune_T c)
{
    return c == 0x0020   /* SPACE */
        || c == 0x1680   /* OGHAM SPACE MARK */
        || (c >= 0x2000 && c <= 0x200A)
        || c == 0x205F   /* MEDIUM MATHEMATICAL SPACE */
        || c == 0x3000;  /* IDEOGRAPHIC SPACE */
}

/* vi:set ts=8 sts=4 sw=4 et: */
