name: GitHub CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  shadow-build:
    runs-on: ubuntu-24.04
    env:
      CC: gcc
      SRCDIR: ./src
      TEST: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable i386
        run: sudo dpkg --add-architecture i386

      - name: Prepare shadow dir
        run: |
          make -C src shadow
          echo "SRCDIR=./src/shadow" >> $GITHUB_ENV
          echo "SHADOWOPT=-C src/shadow" >> $GITHUB_ENV

      - name: Configure
        env:
          # prevent Autoconf from using CI’s SRCDIR
          SRCDIR: ""
        run: |
          cd src/shadow
          ../../configure --with-features=normal --enable-fail-if-missing
          sed -i -f ../../ci/config.mk.sed auto/config.mk
          sed -i -f ../../ci/config.mk.gcc.sed auto/config.mk

      - name: Build
        run: make $SHADOWOPT -j$(nproc)

      - name: Check version
        run: ${{ env.SRCDIR }}/vim --version

      - name: Run tests
        run: make $SHADOWOPT $TEST
